# 
# Настройки модуля тревог и событий
# для использования другого файла, необходимо использовать аргумент
# командной строки и указать полный путь доступа, например
#
#   ./iRo --ae=config/ae.yaml
#

# настройка массива событий
event:
  [
    # act   = бит перехода в активное состояние
    # ack   = бит подтверждения
    # shlvd = бит задержки активации (не реализовано)
    # dsupr = бит запрета активации (не реализовано)
    # oosrv = бит отказа от обслуживания (не реализовано)
    # store = время хранения в массиве, декад 
    # text  = текст для поиска ID 
   { act:  0:0,  store: 110, text: "Задвижка М1.1 Аварийный стоп"},
   { act:  0:1,  store: 110, text: "Задвижка М1.1 Авария"},
   { act:  0:2,  store: 110, text: "Задвижка М1.1 Момент при закрытии больше аварийного"},
   { act:  0:3,  store: 110, text: "Задвижка М1.1 Момент при открытии больше аварийного"},
   { act:  0:4,  store: 110, text: "Задвижка М1.1 Не закрылась"},
   { act:  0:5,  store: 110, text: "Задвижка М1.1 Не открылась"},
   { act:  0:6,  store: 110, text: "Задвижка М1.1 Нет готовности"},
   { act:  0:7,  store: 110, text: "Задвижка М1.1 Отказ блока управления"},
   { act:  0:8,  store: 110, text: "Насос 1. Аварийный стоп"},
   { act:  0:9,  store: 110, text: "Насос 1. Авария"},
   { act:  0:10, store: 110, text: "Насос 1. Время запуска более 10 минут"},
   { act:  0:11, store: 110, text: "Насос 1. Давление выше аварийного"},
   { act:  0:12, store: 110, text: "Насос 1. Давление на всасе выше аварийного"},
   { act:  0:13, store: 110, text: "Насос 1. Давление на всасе ниже аварийного"},
   { act:  0:14, store: 110, text: "Насос 1. Давление на напоре не достигло требуемого"},
   { act:  0:15, store: 110, text: "Насос 1. Давление на напоре снизилось до минимума"},
   { act:  1:0,  store: 110, text: "Насос 1. Давление ниже аварийного"},
   { act:  1:1,  store: 110, text: "Насос 1. Задвижка на всасе самопроизвольно закрылась"},
   { act:  1:2,  store: 110, text: "Насос 1. Задвижка на напоре самопроизвольно закрылась"},
   { act:  1:3,  store: 110, text: "Насос 1. КМШ. Авария по току"},
   { act:  1:4,  store: 110, text: "Насос 1. КМШ. Нет связи с ячейкой"},
   { act:  1:5,  store: 110, text: "Насос 1. Не включился"},
   { act:  1:6,  store: 110, text: "Насос 1. Не отключился"},
   { act:  1:7,  store: 110, text: "Насос 1. Подшипник 1. Виброскорость выше аварийной"},
   { act:  1:8,  store: 110, text: "Насос 1. Подшипник 1. Температура выше аварийной"},
   { act:  1:9,  store: 110, text: "Насос 1. Подшипник 2. Виброскорость выше аварийной"},
   { act:  1:10, store: 110, text: "Насос 1. Подшипник 2. Температура выше аварийной"},
   { act:  1:11, store: 110, text: "Насос 1. Работа на закрытую задвижку"},
   { act:  1:12, store: 110, text: "Насос 1. Расход выше аварийного"},
   { act:  1:13, store: 110, text: "Насос 1. Расход ниже аварийного"},
   { act:  1:14, store: 110, text: "Насос 1. Самопроизвольное отключение"},
   { act:  1:15, store: 110, text: "Насос 1. Самопроизвольный запуск"},
   { act:  2:0,  store: 110, text: "Нет работающих насосов"},
   { act:  2:1,  store: 110, text: "Общий трубопровод 1. Давление выше аварийного"},
   { act:  2:2,  store: 110, text: "Общий трубопровод 1. Давление ниже аварийного"},
   { act:  2:3,  store: 110, text: "Общий трубопровод 2. Давление выше аварийного"},
   { act:  2:4,  store: 110, text: "Общий трубопровод 2. Давление ниже аварийного"},
   { act:  2:5,  store: 110, text: "Общий трубопровод 3. Давление выше аварийного"},
   { act:  2:6,  store: 110, text: "Общий трубопровод 3. Давление ниже аварийного"}
  ]
