# 
# Настройки приложения 
# 
# --config для использования другого файла указываем полный путь доступа в командной строке, например
#   ./iRo --config=config/system.yaml
#
# --info для выдачи полных данных настройки 
#

# Настройки COM портов 
com:
  [
    {
      file: "/dev/ttyS0",        # Имя пвсевдо файла для устройства, например /dev/ttyS0
      baudrate: 115200,          # Аппаратная настройка baudrate, databits, parity, stopbits, по умолчанию 115200,8,N,1
      databits: 8,
      parity: "N",
      stopbits: 1,
      timeout: 8,                # Таймаут (миллисекунды) от начала ожидания данных до рестарта 
      pause: 15                  # Таймаут (микросекунды) перед повторным входом в цикл чтения данных устройства
    }
  ]

# Настройки MODBUS устройств 
modbus:
  {
    rtu:
    [
      {
        node: 1,                  # Адрес ноды MODBUS RTU, по умолчанию 1
        core:                     # настройка данных
        {
          start: 0,               # смещение начала данных блока данных этого устройства, по умолчанию 0
          bytes: 500              # кол-во данных, по умолчанию 0
        }
      }
    ],
    tcp:
    {
      address: 192.168.254.103, # IP адрес устройства, по умолчанию: первый адрес первой сетевой платы
      port: 502,                  # TCP порт, по умолчанию 502
      core:                       # настройка данных
      {
        start: 500,               # смещение начала данных блока данных этого устройства, по умолчанию 0
        bytes: 246                # кол-во данных, по умолчанию 0
      }
    }
  }

# Настройки сервера HTTP
http:
  {
    address: 192.168.254.103,   # Прослушиваемый IP, по умолчанию: первый IP адрес первой сетевой платы
    port: 8080,                   # Прослушиваемый порт, по умолчанию: 80
    read: 60,                     # Ограничение для операций чтения, по умолчанию 60 sec
    write: 15,                    # Ограничение для операций записи, по умолчанию 15 sec
    shutdown: 120,                # Ограничение по времени остановки сервера, по умолчанию 120 sec
    root: "./iRo/web/"            # Корневой каталог, по умолчанию "."
  }
