# 
# Настройки приложения 
# 
# --config для использования другого файла указываем полный путь доступа в командной строке, например
#   ./iRo --config=config/system.yaml
#
# --info для выдачи полных данных настройки 
#

# Настройки COM портов 
com:
  [
    {
      file: "/dev/ttyS0",        # Имя пвсевдо файла для устройства, например /dev/ttyS0
      baudrate: 115200,          # Аппаратная настройка baudrate, databits, parity, stopbits, по умолчанию 115200,8,N,1
      databits: 8,
      parity: "N",
      stopbits: 1,
      timeout: 5,                # Таймаут (миллисекунды) от начала ожидания данных до рестарта, по умолчанию 1 мсек 
    }
  ]

# Настройки MODBUS устройств 
modbus:
  {
    rtu:
    [
      {
        node: 1,                  # Адрес ноды MODBUS RTU, по умолчанию 1
        core:                     # настройка данных
        {
          start: 0,               # смещение начала данных блока данных этого устройства, по умолчанию 0
          bytes: 500              # кол-во данных, по умолчанию 0
        }
      }
    ],
    tcp:
    {
      address: 192.168.254.107,   # IP адрес устройства, по умолчанию: первый адрес первой сетевой платы
      port: 502,                  # TCP порт, по умолчанию 502
      read: 60,                   # Ограничение (секунды) для операций чтения, по умолчанию 60
      write: 15,                  # Ограничение (секунды) для операций записи, по умолчанию 15
      control: 15,                # Период (миллисекунды) запуска команды контроля состояния, по умолчанию 15
      core:                       # настройка данных
      {
        start: 500,               # смещение начала данных блока данных этого устройства, по умолчанию 0
        bytes: 246                # кол-во данных, по умолчанию 0
      }
    }
  }

# Настройки сервера OPC UA
ua:
  {
    port: 54000,                  # Прослушиваемый порт, по умолчанию: 54000
    namespace: 1                  # Идентификатор пространства имен, по умолчанию: 1
  }

# Настройки сервера HTTP
http:
  {
    address: 192.168.254.107,     # Прослушиваемый IP, по умолчанию: первый IP адрес первой сетевой платы
    port: 8080,                   # Прослушиваемый порт, по умолчанию: 80
    read: 60,                     # Ограничение для операций чтения, по умолчанию 60 sec
    write: 15,                    # Ограничение для операций записи, по умолчанию 15 sec
    shutdown: 120,                # Ограничение по времени остановки сервера, по умолчанию 120 sec
#    root: "home/sintep/iRo/web"   # Корневой каталог, по умолчанию "."
    root: "./web"
  }

# Настройки подключения к серверу POSTGRESQL
postgres:
  {
    address: 192.168.254.107,     # Прослушиваемый IP, по умолчанию: первый IP адрес первой сетевой платы
    # prototype: tcp,             # Протокол, по умолчанию: tcp
    # port: 5432,                 # Прослушиваемый порт, по умолчанию: 5432
    timeout: 60000,               # Максимальное время исполнения запроса миллисекунд, по умолчанию: 10000
    # ВНИМАНИЕ! Для повышения сохранности конфиденциальных данных настройки логина и пароля в релизе убираем в переменные окружения
    base: data,                   # Имя базы, по умолчанию: переменная окружения IRO_POSTGRES_DATABASE
    user: user,                   # Имя пользователя, по умолчанию: переменная окружения IRO_POSTGRES_USER
    password: W3.sintep.ru        # Пароль, по умолчанию: переменная окружения IRO_POSTGRES_PASSWORD
  }
